[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[context.production.environment]
  REACT_APP_API_URL = "https://dry-craft-qt3g.vercel.app"
  REACT_APP_MEDIA_URL = "https://dry-craft-qt3g.vercel.app/api/media"
  REACT_APP_MAX_FILE_SIZE = "15728640"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
