services:
  - type: web
    name: dry-craft-backend
    runtime: docker
    plan: starter
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
    healthCheckPath: /actuator/health
