name: Deploy Backend

on:
  push:
    branches: [main]
    paths: ['backend/**']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Run tests
        working-directory: ./backend
        run: ./mvnw test
        
      - name: Build JAR
        working-directory: ./backend
        run: ./mvnw clean package -DskipTests
        
      - name: Build Docker image
        working-directory: ./backend
        run: |
          docker build -t dry-craft-backend:${{ github.sha }} .
          docker tag dry-craft-backend:${{ github.sha }} dry-craft-backend:latest
          
      # Uncomment and configure for your preferred deployment platform
      
      # For Railway deployment
      # - name: Deploy to Railway
      #   uses: railway-deploy@v1
      #   with:
      #     railway_token: ${{ secrets.RAILWAY_TOKEN }}
      #     service: dry-craft-backend
          
      # For Azure Container Apps
      # - name: Login to Azure
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      #     
      # - name: Deploy to Azure Container Apps
      #   working-directory: ./backend
      #   run: |
      #     chmod +x deploy-azure.sh
      #     ./deploy-azure.sh
      
      # For Docker Hub (if using external container registry)
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     
      # - name: Push to Docker Hub
      #   run: |
      #     docker tag dry-craft-backend:latest your-username/dry-craft-backend:latest
      #     docker push your-username/dry-craft-backend:latest
